#!/usr/bin/env python3
"""Generate resources/progs/vau-glue-stubs.scm

The Scheme code of TeXmacs refers to the primitives exported by the C++ glue
(src/Scheme/Glue/build-glue-*.scm). Vau exports only part of them (see
src/Vau/vau_glue.cpp), so we list all the names here and init-vau-s7.scm
defines the ones Vau does not have as procedures which raise an error when
called. Run this script from the root of the repository after updating the
glue tables.
"""
import re, os

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
names = []
for part in ("basic", "editor", "server"):
    src = os.path.join(root, "src/Scheme/Glue/build-glue-%s.scm" % part)
    for line in open(src):
        m = re.match(r"\s*\((\S+)\s+\S+\s+\(", line)
        if m and not line.lstrip().startswith(";"):
            names.append(m.group(1))

out = os.path.join(root, "resources/progs/vau-glue-stubs.scm")
with open(out, "w") as f:
    f.write(""";; Generated by devel/make-glue-stubs.py, do not edit.
;; The primitives of the TeXmacs glue; those missing in Vau become stubs.

(for-each
  (lambda (s)
    (if (not (defined? s (rootlet)))
        (varlet (rootlet) s
          (lambda args
            (error 'vau-not-implemented (symbol->string s))))))
  '(""")
    f.write("\n    ".join(names))
    f.write("))\n")
print("%d glue names written to %s" % (len(names), out))
