//
//  Config.xcconfig.cmake
//  Vau
//
//  Created by Massimiliano Gubinelli on 23/01/2023.
//

// Configuration settings file format documentation can be found at:
// https://help.apple.com/xcode/#/dev745c5c974


Vau_BINARY_DIR= @Vau_BINARY_DIR@
Vau_SOURCE_DIR= @Vau_SOURCE_DIR@
ZLIB_INCLUDE_DIR= @ZLIB_INCLUDE_DIR@
ZLIB_LIBRARY_RELEASE= @ZLIB_LIBRARY_RELEASE@
PNG_LIBRARY_RELEASE= @PNG_LIBRARY_RELEASE@
PNG_PNG_INCLUDE_DIR= @PNG_PNG_INCLUDE_DIR@
Iconv_LIBRARY= @Iconv_LIBRARY@
Iconv_INCLUDE_DIR= @Iconv_INCLUDE_DIR@
FREETYPE_LIBRARY_RELEASE= @FREETYPE_LIBRARY_RELEASE@
FREETYPE_INCLUDE_DIR= @FREETYPE_INCLUDE_DIR_freetype2@
MUPDF_LIBRARIES= @MUPDF_LIBRARY@ @MUPDF_THIRD_LIBRARY@
MUPDF_INCLUDE_DIR= @MUPDF_INCLUDE_DIR@
